"""Build the simulation-only MJCF adapter without changing the source URDF.

Masses and box inertias below are explicit prototype assumptions, not CAD or
hardware measurements. Visual frames and joint coordinates come from the URDF.
The gripper uses force-limited parallel slides; crank/rods are visual followers.
"""
from pathlib import Path
import copy
import hashlib
import json
import os
import xml.etree.ElementTree as ET

import numpy as np
from scipy.spatial.transform import Rotation
import trimesh

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "arm_description_gui_verified_zero/arm_description"
DEST = ROOT / "models/hardstop_arm"
# One lumped mass per moving assembly, including its fixed visual children.
MASSES = dict(zip((1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13),
                  (0.35, 0.8, 0.45, 0.4, 0.3, 0.35, 0.02, 0.06, 0.01, 0.06, 0.01)))


def numbers(values):
    return " ".join(f"{x:.16g}" for x in np.asarray(values).ravel())


def transform(origin):
    t = np.eye(4)
    if origin is not None:
        t[:3, 3] = np.fromstring(origin.get("xyz", "0 0 0"), sep=" ")
        t[:3, :3] = Rotation.from_euler("xyz", np.fromstring(
            origin.get("rpy", "0 0 0"), sep=" ")).as_matrix()
    return t


def pose(t):
    q = Rotation.from_matrix(t[:3, :3]).as_quat()
    return {"pos": numbers(t[:3, 3]), "quat": numbers(q[[3, 0, 1, 2]])}


def build():
    DEST.mkdir(parents=True, exist_ok=True)
    source_file = SOURCE / "urdf/arm_portable.urdf"
    urdf = ET.parse(source_file).getroot()
    links = {x.get("name"): x for x in urdf.findall("link")}
    children = {name: [] for name in links}
    for j in urdf.findall("joint"):
        children[j.find("parent").get("link")].append(j)
    root = ET.Element("mujoco", model="hardstop_arm")
    root.append(ET.Comment("Generated by scripts/tools/build_hardstop_arm.py. "
                           "Simulation mass, inertia, contact and servo assumptions: assumptions.json. "
                           "Source URDF remains authoritative for joint and visual frames."))
    ET.SubElement(root, "compiler", angle="radian", autolimits="true",
                  inertiafromgeom="false", fusestatic="false")
    ET.SubElement(root, "option", timestep="0.002", integrator="implicitfast",
                  solver="Newton", iterations="80", cone="elliptic", gravity="0 0 -9.81")
    visual = ET.SubElement(root, "visual")
    ET.SubElement(visual, "global", offwidth="640", offheight="480")
    ET.SubElement(visual, "map", znear="0.005")
    default = ET.SubElement(root, "default")
    ET.SubElement(default, "joint", damping="0.15", armature="0.005")
    ET.SubElement(default, "geom", friction="1 0.01 0.001", solref="0.008 1",
                  solimp="0.95 0.99 0.001", condim="4")
    asset = ET.SubElement(root, "asset")
    for material in urdf.findall("material"):
        ET.SubElement(asset, "material", name=material.get("name"),
                      rgba=material.find("color").get("rgba"))
    mesh_vertices = {}
    for filename in sorted({x.get("filename") for x in urdf.findall(".//mesh")}):
        path = (source_file.parent / filename).resolve()
        mesh = trimesh.load(path, process=False)
        mesh_vertices[path.stem] = mesh.vertices
        mesh_path = path
        # MuJoCo's STL reader caps a file at 200000 triangles. MSH preserves
        # the large electronics mesh exactly, without decimating the source.
        if len(mesh.faces) > 200000:
            mesh.merge_vertices()
            mesh_path = DEST / f"{path.stem}.msh"
            with mesh_path.open("wb") as f:
                f.write(np.array([len(mesh.vertices), 0, 0, len(mesh.faces)], dtype="<i4").tobytes())
                f.write(np.asarray(mesh.vertices, dtype="<f4").tobytes())
                f.write(np.asarray(mesh.faces, dtype="<i4").tobytes())
        ET.SubElement(asset, "mesh", name=path.stem,
                      file=os.path.relpath(mesh_path, DEST))
    world = ET.SubElement(root, "worldbody")
    ET.SubElement(world, "light", pos="0.2 -0.3 2", dir="0 0 -1", directional="true")
    ET.SubElement(world, "light", pos="-0.5 0.5 1.5", dir="0 0 -1", diffuse="0.4 0.4 0.4")
    bodies, owner_points, moving_joints = {}, {}, {}
    # Bits 2..128 are the base and six arm assemblies; 256 is both fingers.
    all_robot_bits = sum(1 << (i + 1) for i in range(8))

    def add_link(name, parent, t, owner, relative, joint=None):
        body = ET.SubElement(parent, "body", name=name, **pose(t))
        bodies[name] = body
        if joint is not None and joint.get("type") != "fixed":
            owner = int(joint.get("name").removeprefix("joint"))
            relative = np.eye(4)
            lim = joint.find("limit")
            ET.SubElement(body, "joint", name=joint.get("name"),
                          type="slide" if joint.get("type") == "prismatic" else "hinge",
                          axis=joint.find("axis").get("xyz"),
                          range=f"{lim.get('lower')} {lim.get('upper')}")
            moving_joints[owner] = joint
        owner_points.setdefault(owner, [])
        for v in links[name].findall("visual"):
            mesh = Path(v.find("geometry/mesh").get("filename")).stem
            vt = transform(v.find("origin"))
            ET.SubElement(body, "geom", name=f"visual_{name}", type="mesh", mesh=mesh,
                          material=v.find("material").get("name"), contype="0",
                          conaffinity="0", group="1", **pose(vt))
            points = mesh_vertices[mesh]
            rt = relative @ vt
            owner_points[owner].append(points @ rt[:3, :3].T + rt[:3, 3])
            # Crank and rods are decorative in this equivalent gripper model.
            if owner in (7, 11, 13):
                continue
            group = owner if owner <= 6 else 7
            bit = 1 << (group + 1)
            excluded = bit
            if group <= 6:
                for neighbor in (group - 1, group + 1):
                    if 0 <= neighbor <= 7:
                        excluded |= 1 << (neighbor + 1)
            else:
                excluded |= 1 << 7  # fingers vs their own wrist/gripper housing
            ET.SubElement(body, "geom", name=f"collision_{name}", type="mesh", mesh=mesh,
                          contype=str(bit), conaffinity=str(1 | (all_robot_bits & ~excluded)),
                          rgba="0.9 0.2 0.1 0.25", group="3", **pose(vt))
        for child in children[name]:
            ct = transform(child.find("origin"))
            add_link(child.find("child").get("link"), body, ct, owner, relative @ ct, child)

    base = np.eye(4)
    # Move the pedestal 0.10 m toward the task to fit this arm's downward reach.
    # This is a scene placement, not a change to any URDF joint coordinate.
    base[:3, 3] = [0.2, 0.1, 0.2]
    base[:3, :3] = Rotation.from_euler("z", np.pi).as_matrix()
    add_link("link0", world, base, 0, np.eye(4))
    inertia_report = {}
    for owner, mass in MASSES.items():
        points = np.concatenate(owner_points[owner])
        lo, hi = points.min(0), points.max(0)
        lengths = np.maximum(hi - lo, 0.005)
        inertia = mass / 12 * (np.sum(lengths**2) - lengths**2)
        center = (lo + hi) / 2
        bodies[f"link{owner}"].set("gravcomp", "1")
        ET.SubElement(bodies[f"link{owner}"], "inertial", pos=numbers(center),
                      mass=str(mass), diaginertia=numbers(inertia))
        inertia_report[f"link{owner}"] = {"mass_kg": mass, "box_size_m": lengths.tolist(),
                                         "center_m": center.tolist(), "diaginertia": inertia.tolist()}
    ET.SubElement(bodies["link14"], "site", name="tcp_site", size="0.004", rgba="1 0 0 0")
    # Camera orientation chosen for a useful simulation view, not calibrated D415 optics.
    ET.SubElement(bodies["link9"], "camera", name="wrist_cam", pos="0 0.01 -0.055",
                  xyaxes="-1 0 0 0 0.521450009453975 -0.853281833651959", fovy="75")
    equality = ET.SubElement(root, "equality")
    ET.SubElement(equality, "joint", name="jaw_symmetry", joint1="joint12", joint2="joint10",
                  polycoef="0 1 0 0 0", solref="0.004 1")
    actuator = ET.SubElement(root, "actuator")
    for owner, j in moving_joints.items():
        lim = j.find("limit")
        arm = owner <= 6
        slide = owner in (10, 12)
        ET.SubElement(actuator, "position", name=f"servo_joint{owner}", joint=f"joint{owner}",
                      kp="300" if arm else ("1500" if slide else "2"),
                      kv="30" if arm else ("10" if slide else "0.1"),
                      ctrlrange=f"{lim.get('lower')} {lim.get('upper')}",
                      forcerange="-35 35" if arm else ("-12 12" if slide else "-0.2 0.2"))
    ET.indent(root, space="  ")
    ET.ElementTree(root).write(DEST / "robot.xml", encoding="utf-8", xml_declaration=True)

    # Reuse the actual screwdriver, table and bin geometry from the existing task.
    scene = ET.Element("mujoco", model="hardstop_screwdriver_scene")
    ET.SubElement(scene, "include", file="robot.xml")
    original = ET.parse(ROOT / "models/dummyx_apf_scene.xml").getroot()
    assets = copy.deepcopy(original.find("asset"))
    for item in assets:
        if "file" in item.attrib:
            f = item.get("file")
            source = ROOT / "models" / f if f.startswith("meshes/") else ROOT / "models/meshes" / f
            item.set("file", os.path.relpath(source, DEST))
    scene.append(assets)
    scene_world = ET.SubElement(scene, "worldbody")
    for item in original.find("worldbody"):
        if item.get("name") in ("dynamic_pillar", "spawn_area"):
            continue
        element = copy.deepcopy(item)
        if element.get("name") == "rear_cam":
            element.set("pos", "0.75 -0.8 0.85")
            element.set("fovy", "45")
        if element.get("name") == "cam_lookat":
            element.set("pos", "0.15 0.05 0.35")
        scene_world.append(element)
    ET.indent(scene, space="  ")
    ET.ElementTree(scene).write(DEST / "scene.xml", encoding="utf-8", xml_declaration=True)
    report = {
        "source_urdf": str(source_file.relative_to(ROOT)),
        "source_sha256": hashlib.sha256(source_file.read_bytes()).hexdigest(),
        "scope": "simulation prototype; no measured dynamics or hardware validation",
        "inertia_method": "chosen lumped masses; uniform axis-aligned bounding box of each moving assembly",
        "gravity_compensation": "ideal body gravcomp=1; not a calibrated real controller",
        "inertials": inertia_report,
        "gripper": "force-limited parallel slides; nonlinear visual followers; no internal force transmission",
        "collision": "convex hull per URDF visual mesh; adjacent arm assemblies and internal gripper pairs excluded",
        "camera": "simulation wrist view attached to link9; not a calibrated D415 optical frame",
        "base_world_xyz": base[:3, 3].tolist(), "base_world_yaw_rad": float(np.pi),
        "task": "same screwdriver asset, table and drop_box; no obstacle during collection",
    }
    (DEST / "assumptions.json").write_text(json.dumps(report, indent=2) + "\n")
    print(DEST / "scene.xml")


if __name__ == "__main__":
    build()
